"use client";

import {
  BarbellIcon,
  BedIcon,
  BookOpenIcon,
  CameraIcon,
  ChatsCircleIcon,
  CrownIcon,
  DeviceMobileIcon,
  DotsThreeIcon,
  DropIcon,
  EyeIcon,
  FireIcon,
  FlowerIcon,
  GameControllerIcon,
  GhostIcon,
  GiftIcon,
  GlobeIcon,
  HandIcon,
  HeartIcon,
  LightningIcon,
  LinkIcon,
  LockIcon,
  MagicWandIcon,
  MapPinIcon,
  MaskHappyIcon,
  MoonIcon,
  MusicNoteIcon,
  PawPrintIcon,
  PersonIcon,
  SneakerIcon,
  SparkleIcon,
  StarIcon,
  SunIcon,
  TShirtIcon,
  UserIcon,
  UsersThreeIcon,
  WarningDiamondIcon,
  WineIcon,
  type Icon,
} from "@phosphor-icons/react";

/** Icons editors can pick for a category. Keys are stored in the database. */
export const CATEGORY_ICONS: Record<string, Icon> = {
  sparkle: SparkleIcon,
  heart: HeartIcon,
  fire: FireIcon,
  star: StarIcon,
  "magic-wand": MagicWandIcon,
  "t-shirt": TShirtIcon,
  sneaker: SneakerIcon,
  "mask-happy": MaskHappyIcon,
  link: LinkIcon,
  lock: LockIcon,
  lightning: LightningIcon,
  "warning-diamond": WarningDiamondIcon,
  "map-pin": MapPinIcon,
  bed: BedIcon,
  "device-mobile": DeviceMobileIcon,
  camera: CameraIcon,
  eye: EyeIcon,
  hand: HandIcon,
  person: PersonIcon,
  user: UserIcon,
  "users-three": UsersThreeIcon,
  crown: CrownIcon,
  "paw-print": PawPrintIcon,
  drop: DropIcon,
  flower: FlowerIcon,
  gift: GiftIcon,
  wine: WineIcon,
  "music-note": MusicNoteIcon,
  "chats-circle": ChatsCircleIcon,
  "book-open": BookOpenIcon,
  barbell: BarbellIcon,
  "game-controller": GameControllerIcon,
  ghost: GhostIcon,
  globe: GlobeIcon,
  moon: MoonIcon,
  sun: SunIcon,
  "dots-three": DotsThreeIcon,
};

export function CategoryIcon({ name, size = 18, className }: { name: string; size?: number; className?: string }) {
  const Icon = CATEGORY_ICONS[name] ?? SparkleIcon;
  return <Icon size={size} className={className} aria-hidden />;
}
