import type { SeedList } from "@/lib/kinks/types";

export const omni: SeedList = {
  slug: "omni",
  name: "Omni",
  tagline: "Everything, all the options",
  description: "The complete list with every category and every option. For the weird kinky ones.",
  categories: [
    {
      name: "Affection and intimacy",
      icon: "heart",
      description: "Closeness, care, and sensual connection.",
      items: [
        { name: "Kissing", description: "Mouth-to-mouth and mouth-to-body kissing.", variants: ["Soft", "Deep", "Neck", "Body", "Biting lips", "Nose kiss", "Forehead"] },
        { name: "Cuddling", description: "Holding each other close.", roles: ["Big spoon", "Little spoon"], variants: ["Face to face", "Naked", "After sex", "Falling asleep"] },
        { name: "Massage", description: "Rubbing and kneading the body to relax or arouse.", roles: ["Giving", "Receiving"], variants: ["Full body", "Erotic", "Oil", "Nuru", "Tantric"] },
        { name: "Bathing together", description: "Washing and relaxing in water together.", roles: ["Washing", "Being washed"], variants: ["Bubble bath", "Shower", "Hot tub", "Washing hair", "Soap play"] },
        { name: "Romantic dinner", description: "A slow, flirty meal that builds anticipation.", roles: ["Cooking", "Being cooked for"], variants: ["Feeding each other", "Aphrodisiacs", "Naked dinner", "Picnic"] },
        { name: "Sensual dancing", description: "Moving together to music.", roles: ["Leading", "Following"], variants: ["Slow dance", "Grinding", "Lap dance", "Strip tease", "Pole dancing"] },
        { name: "Love letters", description: "Writing out desire and affection, on paper or in long messages.", roles: ["Writing", "Receiving"], variants: ["Romantic", "Explicit", "Poetry"] },
        { name: "Gifts", description: "Presents with a romantic or sexual meaning.", roles: ["Giving", "Receiving"], variants: ["Lingerie", "Toys", "Jewelry", "Flowers", "Surprises"] },
        { name: "Aftercare", description: "Looking after each other once play is over.", roles: ["Giving", "Receiving"], variants: ["Cuddling", "Talking it through", "Cleaning up", "Water and snacks", "Checking in later"] },
      ],
    },
    {
      name: "Sex",
      icon: "fire",
      description: "The core acts most people have an opinion on.",
      items: [
        { name: "Oral sex", description: "Using the mouth on a partner's genitals.", roles: ["Giving", "Receiving", "Mutual (69)"], variants: ["Slow and teasing", "Deep throat", "Swallowing", "Face sitting"] },
        { name: "Manual stimulation", description: "Using hands and fingers on a partner's genitals.", roles: ["Giving", "Receiving"], variants: ["Handjob", "Vaginal fingering", "G-spot or prostate", "Multiple fingers", "Squirting"] },
        { name: "Anal play", description: "Stimulation of the anus, from light touch to full penetration.", roles: ["Giving", "Receiving"], variants: ["Rimming", "Fingers", "Toys", "Penetration", "Watching"] },
        { name: "Masturbation", description: "Pleasuring yourself, alone or with someone involved.", roles: ["Doing it", "Watching a partner", "Being watched"], variants: ["Side by side", "Following instructions", "Over video call"] },
        { name: "Grinding", description: "Rubbing bodies together for friction and arousal.", roles: ["Giving", "Receiving"], variants: ["Clothed", "Naked", "Dry humping"] },
        { name: "Group sex", description: "Sex with more than two people.", variants: ["Threesome", "Foursome", "Orgy", "Swinging", "Gang bang", "Bukkake"] },
      ],
    },
    {
      name: "Flirting and teasing",
      icon: "chats-circle",
      description: "Words, messages, and building anticipation, in person or online.",
      items: [
        { name: "Dirty talk", description: "Saying explicit things out loud to turn each other on.", roles: ["Talking", "Listening"], variants: ["Describing what's happening", "Fantasies", "Moaning and noises"] },
        { name: "Teasing", description: "Building anticipation and holding back satisfaction.", roles: ["Teasing", "Being teased"], variants: ["Verbal", "Physical", "Slow build"] },
        { name: "Praise", description: "Compliments and encouragement during sex.", roles: ["Giving", "Receiving"], variants: ["Good girl or good boy", "Appearance", "Performance"] },
        { name: "Begging", description: "Pleading for something before it's allowed.", roles: ["Begging", "Being begged"], variants: ["For orgasm", "For touch", "For more"] },
        { name: "Sexting", description: "Sending explicit messages, pictures, or videos.", roles: ["Sending", "Receiving"], variants: ["Text", "Photos", "Videos", "Voice messages"] },
        { name: "Phone sex", description: "Turning each other on over a call.", roles: ["Calling", "Being called"], variants: ["Dirty talk", "Roleplay", "Video call"] },
        { name: "Online dating", description: "Meeting people through apps and sites.", variants: ["Casual", "Serious", "Hookups", "Multiple partners"] },
      ],
    },
    {
      name: "Bodies",
      icon: "person",
      description: "What you find attractive in a partner's body.",
      items: [
        { name: "Body type", description: "Overall build.", variants: ["Slim", "Average", "Curvy or chubby", "Muscular"] },
        { name: "Chest size", description: "Size of a partner's chest or breasts.", variants: ["Flat", "Small", "Medium", "Large"] },
        { name: "Butt size", description: "Size of a partner's butt.", variants: ["Small", "Medium", "Large"] },
        { name: "Penis size", description: "Only relevant if your partner has a penis.", variants: ["Small", "Average", "Large"] },
        { name: "Body hair", description: "Hair on the body and around the genitals.", variants: ["Shaved", "Trimmed", "Natural"] },
        { name: "Piercings", description: "Piercings on a partner's body." },
        { name: "Tattoos", description: "Tattoos on a partner's body." },
      ],
    },
    {
      name: "Clothing",
      icon: "t-shirt",
      description: "Outfits, materials, and what is (or isn't) worn.",
      items: [
        { name: "Lingerie", description: "Sexy underwear and intimate outfits.", roles: ["Wearing", "Partner wearing", "Shopping together"], variants: ["Bras", "Panties", "Corsets", "Babydolls", "Crotchless", "Bodysuits"] },
        { name: "Leather", description: "Clothing and gear made of leather.", roles: ["Wearing", "Partner wearing"], variants: ["Pants", "Harnesses", "Gloves", "Boots", "The smell"] },
        { name: "Latex and rubber", description: "Tight, shiny synthetic outfits.", roles: ["Wearing", "Partner wearing"], variants: ["Catsuit", "Gloves", "Hood or mask", "Polished shine", "The smell"] },
        { name: "Stockings and tights", description: "Leg wear that changes the look and feel of legs.", roles: ["Wearing", "Partner wearing"], variants: ["Thigh highs", "Fishnets", "Seamed", "Tearing them"] },
        { name: "High heels", description: "Heels as part of the look, the posture, or the play.", roles: ["Wearing", "Partner wearing"], variants: ["Stilettos", "Boots", "Kept on during sex", "Worship"] },
        { name: "Uniforms", description: "Outfits tied to a job or role.", roles: ["Wearing", "Partner wearing"], variants: ["Nurse", "Police", "Military", "School", "Maid", "Business suit"] },
        { name: "Crossdressing", description: "Wearing clothes usually associated with another gender.", roles: ["Me dressing", "Partner dressing"], variants: ["Partial", "Full look", "Makeup", "Wigs", "In public"] },
        { name: "Nudity", description: "Being naked outside of sex itself.", roles: ["Me naked", "Partner naked"], variants: ["At home", "Sleeping", "Outdoors", "Semi-public"] },
      ],
    },
    {
      name: "Toys",
      icon: "magic-wand",
      description: "Devices and tools made for pleasure.",
      items: [
        { name: "Vibrators", description: "Toys that vibrate for external or internal stimulation.", roles: ["Using on myself", "Using on a partner", "Partner using on me"], variants: ["Bullet", "Wand", "Rabbit", "Couples vibrator"] },
        { name: "Dildos", description: "Non-vibrating toys for penetration.", roles: ["Using on myself", "Using on a partner", "Partner using on me"], variants: ["Realistic", "Fantasy shapes", "Glass", "Silicone", "Double-ended"] },
        { name: "Butt plugs", description: "Anal toys shaped to stay in place.", roles: ["Wearing", "Partner wearing"], variants: ["Small", "Medium", "Large", "Worn for hours", "Tail plug", "Jeweled", "Inflatable"] },
        { name: "Anal beads", description: "A string of beads inserted and pulled out one by one.", roles: ["Using on a partner", "Partner using on me"], variants: ["Small", "Large", "Vibrating", "Pulled out during orgasm"] },
        { name: "Strap-ons", description: "A harness that holds a dildo for penetration.", roles: ["Wearing", "Receiving"], variants: ["Harness", "Strapless", "Double-ended", "Hollow"] },
        { name: "Cock rings", description: "Rings worn at the base of the penis for firmness and sensation.", roles: ["Wearing", "Partner wearing"], variants: ["Silicone", "Metal", "Adjustable", "Vibrating"] },
        { name: "Remote control toys", description: "Toys a partner controls from somewhere else.", roles: ["Controlling", "Being controlled"], variants: ["Long distance", "In public", "Surprise activation", "App controlled"] },
        { name: "Sex machines", description: "Motorized machines built for stimulation.", roles: ["Using", "Operating for a partner"], variants: ["Thrusting machine", "Sybian", "Adjustable speed"] },
      ],
    },
    {
      name: "Locations",
      icon: "map-pin",
      description: "Where it happens.",
      items: [
        { name: "Bedroom", description: "The classic, private setting.", variants: ["Your place", "Partner's place", "On the floor", "In a chair", "Against the wall"] },
        { name: "Shower and bath", description: "Anywhere with water.", variants: ["Shower", "Bath", "Hot tub", "Pool", "Sauna"] },
        { name: "Outdoors", description: "Out in nature.", variants: ["Forest", "Beach", "Garden", "Balcony", "Park", "Camping"] },
        { name: "Car", description: "In or on a vehicle.", variants: ["Back seat", "Front seat", "Parked somewhere quiet", "On the hood"] },
        { name: "Public places", description: "Places where you could get caught.", variants: ["Bathroom", "Changing room", "Elevator", "Movie theater", "Library"] },
        { name: "Kitchen", description: "Counters, tables, and whatever is in the fridge.", variants: ["Counter", "Table", "With food"] },
        { name: "Workplace", description: "An office or workplace, usually after hours.", variants: ["Desk", "Meeting room", "Supply closet", "After hours"] },
        { name: "While traveling", description: "Somewhere away from home.", variants: ["Hotel", "Airplane", "Train", "Cruise", "Vacation rental"] },
      ],
    },
    {
      name: "Roleplay",
      icon: "mask-happy",
      description: "Acting out characters and scenarios.",
      items: [
        { name: "Teacher and student", description: "An authority and learning scenario between adults.", roles: ["Teacher", "Student"], variants: ["Detention", "Private tutoring", "Rewards", "Punishment"] },
        { name: "Doctor and patient", description: "A medical exam scenario.", roles: ["Doctor or nurse", "Patient"], variants: ["Examination", "Treatment", "Medical props"] },
        { name: "Boss and employee", description: "A workplace power scenario.", roles: ["Boss", "Employee"], variants: ["Job interview", "Performance review", "Working late"] },
        { name: "Maid or butler", description: "A service scenario with orders and chores.", roles: ["Giving orders", "Serving"], variants: ["Cleaning", "Formal manners", "Uniform"] },
        { name: "Police and suspect", description: "An arrest and interrogation scenario.", roles: ["Officer", "Suspect"], variants: ["Traffic stop", "Interrogation", "Handcuffs"] },
        { name: "Strangers", description: "Acting like you just met.", variants: ["Bar pickup", "Hotel meeting", "Fake names", "Different personas"] },
        { name: "Fantasy characters", description: "Playing mythical or fictional beings.", roles: ["Me in character", "Partner in character"], variants: ["Vampire", "Werewolf", "Demon", "Angel", "Superhero", "Villain"] },
        { name: "Historical settings", description: "Scenes set in another era, with costumes to match.", variants: ["Medieval", "Victorian", "1950s", "Ancient Rome", "Pirates", "Wild West"] },
      ],
    },
    {
      name: "Sensation",
      icon: "hand",
      description: "Playing with touch, temperature, and texture.",
      items: [
        { name: "Sensory play", description: "Playing with touch, sound, taste, and smell.", roles: ["Giving", "Receiving"], variants: ["Feathers", "Textures", "Blindfolded", "Music", "Scents"] },
        { name: "Hot wax", description: "Dripping warm candle wax on skin.", roles: ["Giving", "Receiving"], variants: ["Low temperature candles", "Colors", "Peeling it off"] },
        { name: "Ice play", description: "Using cold to contrast with warm skin.", roles: ["Giving", "Receiving"], variants: ["Ice cubes", "Nipples", "Genitals", "Full body"] },
        { name: "Tickling", description: "Tickling as play, tease, or torment.", roles: ["Giving", "Receiving"], variants: ["Light", "Intense", "Feathers", "While restrained"] },
      ],
    },
    {
      name: "Bondage",
      icon: "link",
      description: "Restraint and restriction using rope, cuffs, and other gear.",
      items: [
        { name: "Rope bondage", description: "Tying someone up for restraint or for the look of it.", roles: ["Tying", "Being tied"], variants: ["Shibari", "Hogtie", "Spread eagle", "Suspension"] },
        { name: "Cuffs", description: "Cuffs for wrists or ankles.", roles: ["Cuffing", "Being cuffed"], variants: ["Metal", "Fuzzy", "Leather", "Behind the back", "To the bed"] },
        { name: "Blindfolds", description: "Taking away sight to sharpen everything else.", roles: ["Blindfolding", "Being blindfolded"], variants: ["Sleep mask", "Scarf", "Hood"] },
        { name: "Gags", description: "Something in or over the mouth to muffle speech.", roles: ["Gagging", "Being gagged"], variants: ["Ball gag", "Bit gag", "Ring gag", "Tape", "Cloth"] },
        { name: "Spreader bars", description: "A bar that keeps legs or arms apart.", roles: ["Using", "Being restrained"], variants: ["Ankles", "Wrists", "Adjustable"] },
        { name: "Restraint furniture", description: "Furniture built for tying someone in place.", roles: ["Using", "Being restrained"], variants: ["St. Andrew's cross", "Bondage bed", "Stocks", "Suspension frame"] },
      ],
    },
    {
      name: "Pain and impact",
      icon: "lightning",
      description: "Striking, pinching, and biting, from playful to intense.",
      items: [
        { name: "Spanking", description: "Striking the butt or thighs with a hand or paddle.", roles: ["Giving", "Receiving"], variants: ["Hand", "Paddle", "Light and playful", "Hard", "Over clothes", "Bare", "As punishment"] },
        { name: "Flogging", description: "A multi-tailed flogger across the back, butt, or thighs.", roles: ["Giving", "Receiving"], variants: ["Thuddy", "Stingy", "Leather", "Suede", "Rubber"] },
        { name: "Caning", description: "A thin, flexible cane that gives sharp, precise strokes.", roles: ["Giving", "Receiving"], variants: ["Light", "Heavy", "Leaving marks"] },
        { name: "Whipping", description: "Single-tail whips. Needs real skill to do safely.", roles: ["Giving", "Receiving"], variants: ["Single tail", "Signal whip", "Sound of the crack", "Leaving marks"] },
        { name: "Nipple play", description: "Pinching, clamping, or pulling the nipples.", roles: ["Giving", "Receiving"], variants: ["Pinching", "Clamps", "Clothespins", "Weights", "Chains", "Suction"] },
        { name: "Hair pulling", description: "Holding or tugging hair during sex or kissing.", roles: ["Doing", "Receiving"], variants: ["Gentle grip", "Firm pull", "During sex", "During kissing"] },
        { name: "Scratching and biting", description: "Nails and teeth, from light traces to marks.", roles: ["Giving", "Receiving"], variants: ["Light", "Deep", "Leaving marks", "Back", "Neck"] },
      ],
    },
    {
      name: "Power and control",
      icon: "crown",
      description: "Dominance, submission, and who gets to decide.",
      items: [
        { name: "Power exchange", description: "One person takes control and the other gives it up, by agreement.", roles: ["Dominant", "Submissive", "Switch"], variants: ["Only during sex", "Ongoing (24/7)", "Rules and protocols", "Service"] },
        { name: "Orgasm control", description: "Deciding when, how, or if someone gets to come.", roles: ["In control", "Being controlled"], variants: ["Edging", "Denial", "Needing permission", "Forced orgasms", "Ruined orgasms"] },
        { name: "Humiliation", description: "Embarrassment or degradation that turns someone on.", roles: ["Giving", "Receiving"], variants: ["Verbal", "Physical", "Mild", "Intense", "In front of others"] },
        { name: "Chastity", description: "A device that blocks touching or getting off.", roles: ["Wearing", "Keyholder"], variants: ["Short term", "Long term", "Teasing while locked"] },
        { name: "Collars and leashes", description: "A collar as a sign of ownership or submission.", roles: ["Wearing", "Partner wearing"], variants: ["Everyday collar", "Play collar", "Locking", "Leash"] },
        { name: "Cages", description: "Being kept in an enclosure.", roles: ["Caging", "Being caged"], variants: ["Small", "Large", "As punishment", "On display"] },
        { name: "Pet play", description: "Taking on an animal persona and being treated like one.", roles: ["Pet", "Owner"], variants: ["Puppy", "Kitten", "Pony", "Training", "Collar and leash"] },
      ],
    },
    {
      name: "Watching and being watched",
      icon: "eye",
      description: "Audiences, cameras, and screens.",
      items: [
        { name: "Exhibitionism and voyeurism", description: "Watching others, or being watched, during sex or undressing.", roles: ["Being watched", "Watching"], variants: ["Strangers", "Friends", "Online", "Through a window", "Semi-public"] },
        { name: "Photos and video", description: "Recording intimate moments.", roles: ["Filming or photographing", "Being filmed or photographed"], variants: ["Photos", "Video", "Polaroid", "Nude portraits", "During sex"] },
        { name: "Cam shows", description: "Live video performances.", roles: ["Performing", "Watching"], variants: ["Private", "Public", "Solo", "Couples", "Tipping"] },
        { name: "Porn", description: "Watching adult content.", roles: ["Alone", "Together"], variants: ["Amateur", "Professional", "Interactive", "Making our own"] },
        { name: "Virtual reality", description: "Immersive VR experiences.", variants: ["VR porn", "Interactive", "Avatars", "Haptic feedback"] },
      ],
    },
    {
      name: "Fetishes",
      icon: "star",
      description: "Specific objects, body parts, or scenarios with an erotic focus.",
      items: [
        { name: "Feet", description: "Attraction to feet and everything around them.", roles: ["Giving attention", "Receiving attention"], variants: ["Worship", "Massage", "Kissing and licking", "Toes", "Soles", "Socks", "Shoes"] },
        { name: "Food play", description: "Using food on bodies for taste, texture, and mess.", roles: ["Giving", "Receiving"], variants: ["Eating off the body", "Whipped cream", "Chocolate", "Fruit", "Messy"] },
        { name: "Smoking", description: "Finding smoking attractive in a sexual context.", roles: ["Smoking", "Watching"], variants: ["Cigarettes", "Cigars", "Blowing smoke"] },
        { name: "Balloons", description: "Sexual play with balloons.", variants: ["Inflating", "Popping", "Sitting on them", "Rubbing"] },
        { name: "Transformation", description: "Fantasies about changing form, body, or species.", variants: ["Gender", "Animal", "Object", "Size", "Magical", "Gradual"] },
      ],
    },
    {
      name: "Taboo and edge play",
      icon: "warning-diamond",
      description: "Widely off-limits or higher-risk play. Always between consenting adults, with research and care.",
      items: [
        { name: "Age play", description: "Roleplay where consenting adults act older or younger.", roles: ["Caregiver", "Little"], variants: ["Daddy or mommy dynamic", "Diapers", "Pacifiers"] },
        { name: "Incest roleplay", description: "Fantasy scenarios about family roles, between unrelated consenting adults.", variants: ["Parent and child roles", "Siblings", "Step-family", "Taboo talk"] },
        { name: "Watersports", description: "Play involving urine.", roles: ["Giving", "Receiving"], variants: ["Golden shower", "Marking", "Drinking", "Wetting", "Desperation"] },
        { name: "Scat play", description: "Play involving feces. Carries serious health risks.", roles: ["Giving", "Receiving"], variants: ["Watching", "Smearing", "Eating", "Diapers"] },
        { name: "Breath play", description: "Restricting breathing for intensity. One of the most dangerous practices; never do it alone.", roles: ["Giving", "Receiving"], variants: ["Hand on throat", "Breath holding", "Plastic bags", "Gas masks", "Underwater"] },
        { name: "Medical play", description: "Using medical tools and procedures in a scene.", roles: ["Giving", "Receiving"], variants: ["Examinations", "Temperature", "Stethoscope", "Speculum", "Enemas", "Catheters"] },
      ],
    },
  ],
};
