import type { SeedList } from "@/lib/kinks/types";

export const omni: SeedList = {
  slug: "omni",
  name: "Omni",
  tagline: "Everything, all the options",
  description: "The complete list with every category and every option. For the weird kinky ones.",
  categories: [
    {
      name: "General",
      description: "Basic kinks and fetishes that are commonly explored.",
      items: [
        { name: "Anal play", description: "Comprehensive anal activities including fingering, rimming, toys, and penetration with various techniques and intensities.", options: ["Giving", "Receiving", "Watching", "Rimming", "Fingering", "Toys", "Penetration"] },
        { name: "Oral sex", description: "Extensive oral stimulation techniques including different positions, depths, and styles of giving and receiving pleasure.", options: ["Giving", "Receiving", "Mutual", "Deep throat", "Teasing", "Swallowing", "69"] },
        { name: "Spanking", description: "Impact play using hands on various body parts with different intensities, positions, and emotional contexts.", options: ["Giving", "Receiving", "Watching", "Light", "Hard", "Over clothes", "Bare", "Punishment", "Playful"] },
        { name: "Hair pulling", description: "Various techniques of hair manipulation from gentle tugging to firm grips during different activities.", options: ["Doing", "Receiving", "Gentle", "Firm", "During sex", "During kissing"] },
        { name: "Dirty talk", description: "Verbal communication during intimate activities including descriptions, commands, praise, and degradation.", options: ["Talking", "Listening", "Commanding", "Praising", "Degrading", "Begging"] },
        { name: "Fingering", description: "Manual stimulation using fingers with various techniques, speeds, and combinations for different types of pleasure.", options: ["Giving", "Receiving", "Vaginal", "Anal", "Multiple fingers", "G-spot", "Squirting"] },
        { name: "Masturbation", description: "Self-stimulation activities in various contexts including solo, mutual, instructed, and watched scenarios.", options: ["Solo", "Mutual", "Watching", "Being watched", "Instructed", "Phone sex", "Video chat"] },
      ],
    },
    {
      name: "Toys",
      description: "Various toys and implements used in intimate activities.",
      items: [
        { name: "Vibrators", description: "Electronic stimulation devices with various features, intensities, and applications for different body parts.", options: ["Using on self", "Using on partner", "Partner using on me", "Bullet", "Wand", "Rabbit", "Remote control"] },
        { name: "Dildos", description: "Non-vibrating penetrative toys in various sizes, shapes, and materials for different types of play.", options: ["Using", "Partner using", "Double-ended", "Realistic", "Fantasy", "Glass", "Silicone"] },
        { name: "Butt plugs", description: "Anal toys designed for insertion and wearing with various sizes, shapes, and special features.", options: ["Small", "Medium", "Large", "Wearing long-term", "Tail plugs", "Jeweled", "Inflatable"] },
        { name: "Handcuffs", description: "Restraint devices for wrists in various materials and styles from decorative to secure bondage.", options: ["Using", "Wearing", "Fuzzy", "Metal", "Leather", "Chain", "Behind back", "To bed"] },
        { name: "Cock rings", description: "Rings for penis and testicles with various features for enhanced sensation, endurance, and appearance.", options: ["Wearing", "Partner wearing", "Vibrating", "Adjustable", "Metal", "Silicone", "With prostate stimulator"] },
        { name: "Strap-ons", description: "Harness and dildo combinations for penetrative play with various configurations and accessories.", options: ["Wearing", "Partner wearing", "Receiving", "Double-ended", "Strapless", "Hollow", "Realistic"] },
        { name: "Nipple toys", description: "Devices and accessories specifically designed for nipple stimulation and sensation play.", options: ["Clamps", "Suction", "Vibrating", "Weights", "Chains", "Pumps", "Jewelry"] },
      ],
    },
    {
      name: "Clothing",
      description: "Clothing-related fetishes and preferences.",
      items: [
        { name: "Lingerie", description: "Sexy undergarments and intimate apparel including various styles, materials, and purposes.", options: ["Wearing", "Partner wearing", "Shopping for", "Bras", "Panties", "Corsets", "Babydolls", "Crotchless"] },
        { name: "Leather", description: "Clothing and accessories made from leather including various garments and their associated sensations.", options: ["Wearing", "Partner wearing", "Smell", "Pants", "Corsets", "Harnesses", "Gloves", "Boots"] },
        { name: "Latex/Rubber", description: "Tight-fitting synthetic materials that create unique sensations, appearance, and psychological effects.", options: ["Wearing", "Partner wearing", "Full body", "Catsuit", "Gloves", "Masks", "Smell", "Shining"] },
        { name: "Stockings/Pantyhose", description: "Leg coverings that enhance appearance and provide tactile sensations in various styles and contexts.", options: ["Wearing", "Partner wearing", "Ripping off", "Thigh highs", "Fishnet", "Seamed", "Worship"] },
        { name: "High heels", description: "Footwear that changes posture and adds height, often considered sexy and used in various scenarios.", options: ["Wearing", "Partner wearing", "Worship", "Trampling", "Stilettos", "Boots", "During sex"] },
        { name: "Uniforms", description: "Specific clothing associated with professions or roles for roleplay scenarios and fantasy fulfillment.", options: ["Wearing", "Partner wearing", "Nurse", "Police", "Military", "School", "Maid", "Business"] },
        { name: "Crossdressing", description: "Wearing clothing typically associated with a different gender for various purposes and scenarios.", options: ["Self", "Partner", "Full transformation", "Partial", "Makeup", "Wigs", "Public"] },
      ],
    },
    {
      name: "Roleplay",
      description: "Different scenarios and character-based activities.",
      items: [
        { name: "Teacher/Student", description: "Educational authority dynamics with power exchange, learning scenarios, and various educational settings.", options: ["Teacher", "Student", "Detention", "Private tutoring", "Punishment", "Rewards", "Uniform"] },
        { name: "Doctor/Patient", description: "Medical examination scenarios with professional elements, intimate examinations, and healthcare roleplay.", options: ["Doctor", "Patient", "Nurse", "Examination", "Treatment", "Medical equipment", "Hospital"] },
        { name: "Boss/Employee", description: "Workplace power dynamics with authority, submission, professional settings, and career consequences.", options: ["Boss", "Employee", "Interview", "Performance review", "Overtime", "Office", "Promotion"] },
        { name: "Maid/Master", description: "Service-oriented roleplay with domestic duties, personal care, and various levels of formality.", options: ["Maid", "Master", "French maid", "Butler", "Cleaning", "Service", "Uniform", "Orders"] },
        { name: "Police/Criminal", description: "Law enforcement scenarios with authority, interrogation, consequences, and justice themes.", options: ["Police", "Criminal", "Arrest", "Interrogation", "Handcuffs", "Uniform", "Traffic stop"] },
        { name: "Stranger scenarios", description: "Meeting and interacting as if strangers in various settings and situations for excitement and novelty.", options: ["Pickup", "Bar meeting", "Online dating", "Vacation", "Hotel", "Fake names", "Different personas"] },
        { name: "Fantasy characters", description: "Taking on fictional or mythical personas for creative and imaginative roleplay scenarios.", options: ["Vampire", "Werewolf", "Fairy", "Demon", "Angel", "Superhero", "Villain", "Medieval"] },
      ],
    },
    {
      name: "Bondage",
      description: "Restraint, restriction, and control using rope, cuffs, and other devices.",
      items: [
        { name: "Rope bondage", description: "Using rope for restraint, artistic purposes, and creating beautiful patterns with various techniques and styles.", options: ["Tying", "Being tied", "Shibari", "Kinbaku", "Suspension", "Hogtie", "Spread eagle", "Artistic"] },
        { name: "Blindfolding", description: "Removing sight to heighten other senses, create anticipation, and enhance psychological elements.", options: ["Blindfolding", "Being blindfolded", "Sensory deprivation", "Sleep mask", "Scarf", "Hood"] },
        { name: "Gagging", description: "Restricting speech using various types of gags for control, humiliation, and sensory experiences.", options: ["Gagging", "Being gagged", "Ball gag", "Bit gag", "Tape", "Panties", "Ring gag", "Inflatable"] },
        { name: "Spreader bars", description: "Devices that keep limbs apart, preventing closure and creating vulnerability in various positions.", options: ["Using", "Wearing", "Ankle", "Wrist", "Adjustable", "Fixed", "Standing", "Lying"] },
        { name: "Restraint furniture", description: "Specialized furniture designed for bondage including various pieces for different positions and activities.", options: ["Using", "Being restrained", "St. Andrew's cross", "Bondage bed", "Stocks", "Pillory", "Suspension frame"] },
        { name: "Chastity devices", description: "Devices that prevent sexual activity or stimulation for control, denial, and power exchange.", options: ["Wearing", "Partner wearing", "Key holding", "Male", "Female", "Long-term", "Teasing"] },
        { name: "Collars", description: "Neck accessories that symbolize ownership, submission, and various relationship dynamics.", options: ["Wearing", "Partner wearing", "Day collar", "Play collar", "Locking", "Leash", "Training"] },
      ],
    },
    {
      name: "Pain",
      description: "Impact, sensation, and pain play at different intensities.",
      items: [
        { name: "Light spanking", description: "Gentle impact play using hands for warming up, light sensation, and playful interactions.", options: ["Giving", "Receiving", "Over clothes", "Bare", "Playful", "Punishment", "Warm-up", "Cool-down"] },
        { name: "Paddle spanking", description: "Using paddles for more intense impact play with different materials, textures, and techniques.", options: ["Giving", "Receiving", "Leather", "Wood", "Rubber", "Holes", "Textured", "Fraternity"] },
        { name: "Flogging", description: "Using floggers with multiple tails for varied sensations across different body parts and intensities.", options: ["Giving", "Receiving", "Leather", "Suede", "Rubber", "Heavy", "Light", "Thuddy", "Stingy"] },
        { name: "Caning", description: "Using canes for precise, intense impact play that creates specific sensations and marks.", options: ["Giving", "Receiving", "Light", "Heavy", "Rattan", "Synthetic", "Stripes", "Punishment"] },
        { name: "Whipping", description: "Using single-tail whips for advanced impact play requiring skill and creating intense sensations.", options: ["Giving", "Receiving", "Single tail", "Bull whip", "Signal whip", "Cracking", "Marking"] },
        { name: "Nipple clamps", description: "Devices that apply adjustable pressure to nipples for pain, pleasure, and extended sensation.", options: ["Wearing", "Partner wearing", "Chain", "Weights", "Clover", "Clothespin", "Magnetic", "Vibrating"] },
        { name: "Hot wax", description: "Dripping warm wax on the body for temperature play, sensation, and artistic purposes.", options: ["Giving", "Receiving", "Candles", "Different temperatures", "Massage", "Removal", "Colors"] },
        { name: "Ice play", description: "Using cold temperatures for contrasting sensations, temperature play, and shock value.", options: ["Giving", "Receiving", "Cubes", "Melting", "Insertion", "Nipples", "Genitals", "Full body"] },
        { name: "Pinching", description: "Using fingers or devices to create sharp, localized sensations on various body parts.", options: ["Giving", "Receiving", "Nipples", "Thighs", "Arms", "Clothespins", "Fingers", "Twisting"] },
      ],
    },
    {
      name: "Taboo",
      description: "More extreme or unconventional preferences.",
      items: [
        { name: "Age play", description: "Roleplay involving age differences or regression scenarios with consenting adults in various contexts.", options: ["Older", "Younger", "Caregiver", "Little", "Daddy", "Mommy", "Diaper", "Pacifier"] },
        { name: "Pet play", description: "Taking on animal personas with associated behaviors, care dynamics, and various animal types.", options: ["Pet", "Owner", "Puppy", "Kitten", "Pony", "Fox", "Training", "Collar", "Leash"] },
        { name: "Watersports", description: "Activities involving urine in various contexts, scenarios, and levels of involvement.", options: ["Giving", "Receiving", "Golden shower", "Marking", "Drinking", "Wetting", "Desperation"] },
        { name: "Scat play", description: "Activities involving feces in various contexts and levels of involvement.", options: ["Giving", "Receiving", "Smearing", "Eating", "Watching", "Diaper"] },
        { name: "Exhibitionism", description: "Being seen by others during intimate activities or in states of undress in various settings.", options: ["Being watched", "Watching", "Public", "Semi-public", "Strangers", "Friends", "Online", "Windows"] },
        { name: "Voyeurism", description: "Watching others during intimate activities with their knowledge and consent in various scenarios.", options: ["Watching", "Being watched", "Couples", "Solo", "Masturbation", "Sex", "Undressing", "Sleeping"] },
        { name: "Group activities", description: "Intimate activities involving more than two people in various configurations and dynamics.", options: ["Threesome", "Foursome", "Orgy", "Swinging", "Gang bang", "Bukkake", "Circle jerk", "Daisy chain"] },
      ],
    },
    {
      name: "Romantic",
      description: "Affection, intimacy, and sensual connection.",
      items: [
        { name: "Massage", description: "Sensual touching and body work for relaxation, arousal, and connection with various techniques.", options: ["Giving", "Receiving", "Full body", "Erotic", "Oil", "Nuru", "Tantric", "Hot stone"] },
        { name: "Kissing", description: "Various forms of lip and mouth contact from gentle to passionate in different contexts.", options: ["Light", "Deep", "Neck", "Body", "French", "Butterfly", "Eskimo", "Forehead"] },
        { name: "Cuddling", description: "Close physical contact and embracing for comfort, intimacy, and emotional connection.", options: ["Big spoon", "Little spoon", "Face to face", "Naked", "Clothed", "After sex", "Sleeping"] },
        { name: "Sensual bathing", description: "Intimate washing and care activities in water settings with various elements and purposes.", options: ["Giving", "Receiving", "Together", "Bubble bath", "Shower", "Hot tub", "Washing hair", "Soap play"] },
        { name: "Romantic dinner", description: "Intimate dining experiences that enhance connection, anticipation, and sensual pleasure.", options: ["Cooking", "Being cooked for", "Feeding", "Aphrodisiacs", "Naked", "Formal", "Picnic"] },
        { name: "Dancing", description: "Moving together to music in intimate and sensual ways for connection and arousal.", options: ["Leading", "Following", "Slow", "Grinding", "Lap dance", "Strip tease", "Pole dancing"] },
        { name: "Love letters", description: "Written expressions of desire, love, and intimate thoughts for emotional and sexual connection.", options: ["Writing", "Receiving", "Erotic", "Romantic", "Poetry", "Sexting", "Email"] },
      ],
    },
    {
      name: "Locations",
      description: "Different settings and environments for activities.",
      items: [
        { name: "Bedroom", description: "Traditional intimate space with comfort, privacy, and various furniture and settings.", options: ["Own", "Partner's", "Hotel", "Different beds", "Floor", "Chair", "Against wall"] },
        { name: "Shower/Bath", description: "Water-based intimate activities with unique sensations, cleanliness, and various water features.", options: ["Shower", "Bath", "Hot tub", "Pool", "Jacuzzi", "Steam room", "Waterfall", "Beach"] },
        { name: "Outdoors", description: "Nature-based intimate encounters with risk, natural settings, and various outdoor environments.", options: ["Forest", "Beach", "Garden", "Balcony", "Park", "Mountain", "Desert", "Camping"] },
        { name: "Car", description: "Vehicle-based intimate activities with space constraints, mobility, and various car types.", options: ["Backseat", "Front seat", "Parked", "Moving", "Truck", "Limo", "Motorcycle", "RV"] },
        { name: "Public places", description: "Semi-public locations with risk of discovery, excitement, and various levels of exposure.", options: ["Bathroom", "Changing room", "Office", "Elevator", "Library", "Movie theater", "Restaurant"] },
        { name: "Kitchen", description: "Food-related intimate activities and domestic settings with various surfaces and food items.", options: ["Counter", "Table", "Floor", "With food", "Refrigerator", "Against appliances", "Cooking together"] },
        { name: "Workplace", description: "Professional settings used for intimate activities with power dynamics and risk factors.", options: ["Office", "Conference room", "Desk", "After hours", "Boss's office", "Supply closet", "Break room"] },
      ],
    },
    {
      name: "Fetishes",
      description: "Specific objects, body parts, or scenarios with an erotic focus.",
      items: [
        { name: "Feet", description: "Attraction to feet including various activities, worship, and different aspects of feet.", options: ["Worship", "Massage", "Kissing", "Licking", "Toes", "Soles", "Shoes", "Socks"] },
        { name: "Smoking", description: "Attraction to smoking or the act of smoking in intimate contexts and scenarios.", options: ["Watching", "Doing", "Cigarettes", "Cigars", "Pipes", "Blowing smoke", "Ash play"] },
        { name: "Balloons", description: "Various activities involving balloons for sensual, sexual, or fetishistic purposes.", options: ["Inflating", "Popping", "Sitting", "Rubbing", "Latex", "Different sizes", "Helium"] },
        { name: "Food play", description: "Using food items in intimate activities for taste, texture, and sensual experiences.", options: ["Eating off body", "Feeding", "Messy", "Whipped cream", "Chocolate", "Fruit", "Ice cream"] },
        { name: "Medical play", description: "Activities involving medical equipment, procedures, and scenarios for various purposes.", options: ["Examination", "Injection", "Enema", "Catheter", "Speculum", "Temperature", "Stethoscope"] },
        { name: "Breath play", description: "Activities involving controlled breathing for enhanced sensations and psychological effects.", options: ["Choking", "Breath holding", "Plastic bags", "Gas masks", "Underwater", "Hyperventilation"] },
        { name: "Tickling", description: "Using touch to create tickling sensations for playfulness, torture, or sensual purposes.", options: ["Giving", "Receiving", "Light", "Intense", "Feathers", "Fingers", "Restraint", "Torture"] },
      ],
    },
    {
      name: "Technology",
      description: "Digital, remote, and device-based play.",
      items: [
        { name: "Sexting", description: "Sending sexually explicit messages, images, or videos through digital communication.", options: ["Sending", "Receiving", "Text", "Photos", "Videos", "Voice messages", "Apps", "Anonymous"] },
        { name: "Cam shows", description: "Live video performances for sexual entertainment and interaction with viewers.", options: ["Performing", "Watching", "Private", "Public", "Couples", "Solo", "Interactive", "Tipping"] },
        { name: "Virtual reality", description: "Using VR technology for immersive sexual experiences and fantasy scenarios.", options: ["Watching", "Participating", "POV", "Interactive", "Fantasy worlds", "Avatars", "Haptic feedback"] },
        { name: "Sex machines", description: "Mechanical devices designed for sexual stimulation with various features and capabilities.", options: ["Using", "Partner using", "Fucking machine", "Sybian", "Remote control", "Adjustable speed"] },
        { name: "Remote control toys", description: "Sex toys that can be controlled remotely for long-distance play and public use.", options: ["Using", "Partner using", "Public", "Long distance", "App controlled", "Surprise activation"] },
        { name: "Phone sex", description: "Intimate conversations over the phone for sexual arousal and satisfaction.", options: ["Calling", "Receiving", "Dirty talk", "Masturbation", "Roleplay", "Stranger", "Regular partner"] },
        { name: "Online dating", description: "Meeting people through digital platforms for various types of relationships and encounters.", options: ["Casual", "Serious", "Hookups", "Multiple partners", "Profiles", "Messaging", "Video calls"] },
      ],
    },
    {
      name: "Misc",
      description: "Other preferences that don't fit into standard categories.",
      items: [
        { name: "Photography", description: "Taking pictures during intimate moments for memory, artistic purposes, and sharing.", options: ["Taking photos", "Being photographed", "Video", "Polaroid", "Professional", "Amateur", "Nude", "Action"] },
        { name: "Role reversal", description: "Switching typical roles or dynamics for variety, exploration, and power exchange.", options: ["Dom/sub", "Top/bottom", "Active/passive", "Gender roles", "Age roles", "Power dynamics"] },
        { name: "Sensory play", description: "Activities focusing on different senses beyond sight including touch, sound, taste, and smell.", options: ["Giving", "Receiving", "Feathers", "Textures", "Blindfolded", "Music", "Scents", "Temperature"] },
        { name: "Edging", description: "Bringing to the brink of climax repeatedly without allowing release for extended pleasure.", options: ["Giving", "Receiving", "Self", "Extended", "Multiple times", "Ruined orgasm", "Denial"] },
        { name: "Orgasm control", description: "Managing and controlling climax timing, intensity, and permission for power exchange.", options: ["Controlling", "Being controlled", "Denial", "Permission", "Forced", "Multiple", "Ruined"] },
        { name: "Aftercare", description: "Post-activity care and attention for emotional and physical well-being and connection.", options: ["Giving", "Receiving", "Cuddling", "Talking", "Cleaning", "Hydration", "Checking in", "Debriefing"] },
        { name: "Humiliation", description: "Activities involving embarrassment, degradation, or shame for psychological arousal.", options: ["Giving", "Receiving", "Verbal", "Physical", "Public", "Private", "Mild", "Extreme"] },
        { name: "Praise", description: "Positive reinforcement and compliments during intimate activities for encouragement and arousal.", options: ["Giving", "Receiving", "Good girl/boy", "Verbal", "Physical", "Performance", "Appearance", "Effort"] },
        { name: "Begging", description: "Pleading or asking for permission, pleasure, or relief in various intimate contexts.", options: ["Doing", "Hearing", "Permission", "Orgasm", "Touch", "Stop", "More", "Please"] },
        { name: "Teasing", description: "Playful or torturous activities that build anticipation and arousal without immediate satisfaction.", options: ["Giving", "Receiving", "Verbal", "Physical", "Denial", "Anticipation", "Slow", "Extended"] },
      ],
    },
  ],
};
