import type { SeedList } from "@/lib/kinks/types";

export const uncommon: SeedList = {
  slug: "uncommon",
  name: "Uncommon",
  tagline: "More depth, more options",
  description: "A broader list with more categories and more ways to answer each item. For the horny ones.",
  categories: [
    {
      name: "Affection and intimacy",
      icon: "heart",
      description: "Closeness, care, and sensual connection.",
      items: [
        { name: "Kissing", description: "Mouth-to-mouth and mouth-to-body kissing.", variants: ["Soft", "Deep", "Neck", "Body"] },
        { name: "Cuddling", description: "Holding each other close.", roles: ["Big spoon", "Little spoon"], variants: ["Face to face"] },
        { name: "Massage", description: "Rubbing and kneading the body to relax or arouse.", roles: ["Giving", "Receiving"], variants: ["Full body", "Erotic"] },
        { name: "Bathing together", description: "Washing and relaxing in water together.", roles: ["Washing", "Being washed"], variants: ["Bubble bath"] },
        { name: "Romantic dinner", description: "A slow, flirty meal that builds anticipation.", roles: ["Cooking", "Being cooked for"], variants: ["Feeding each other", "Aphrodisiacs"] },
        { name: "Sensual dancing", description: "Moving together to music.", roles: ["Leading", "Following"], variants: ["Slow dance", "Grinding"] },
        { name: "Aftercare", description: "Looking after each other once play is over.", roles: ["Giving", "Receiving"], variants: ["Cuddling", "Talking it through"] },
      ],
    },
    {
      name: "Sex",
      icon: "fire",
      description: "The core acts most people have an opinion on.",
      items: [
        { name: "Oral sex", description: "Using the mouth on a partner's genitals.", roles: ["Giving", "Receiving", "Mutual (69)"] },
        { name: "Fingering", description: "Using fingers to stimulate a partner.", roles: ["Giving", "Receiving"] },
        { name: "Anal play", description: "Stimulation of the anus, from fingers and toys to penetration.", roles: ["Giving", "Receiving"], variants: ["Fingers", "Toys", "Penetration"] },
        { name: "Masturbation", description: "Pleasuring yourself, alone or with someone involved.", roles: ["Doing it", "Watching a partner", "Being watched"] },
        { name: "Group sex", description: "Sex with more than two people.", variants: ["Threesome", "Foursome", "Orgy", "Swinging"] },
      ],
    },
    {
      name: "Flirting and teasing",
      icon: "chats-circle",
      description: "Words, messages, and building anticipation.",
      items: [
        { name: "Dirty talk", description: "Saying explicit things out loud to turn each other on.", roles: ["Talking", "Listening"] },
        { name: "Teasing", description: "Building anticipation and holding back satisfaction.", roles: ["Teasing", "Being teased"], variants: ["Verbal", "Physical", "Slow build"] },
      ],
    },
    {
      name: "Bodies",
      icon: "person",
      description: "What you find attractive in a partner's body.",
      items: [
        { name: "Body type", description: "Overall build.", variants: ["Slim", "Average", "Curvy or chubby", "Muscular"] },
        { name: "Chest size", description: "Size of a partner's chest or breasts.", variants: ["Flat", "Small", "Medium", "Large"] },
        { name: "Butt size", description: "Size of a partner's butt.", variants: ["Small", "Medium", "Large"] },
        { name: "Penis size", description: "Only relevant if your partner has a penis.", variants: ["Small", "Average", "Large"] },
        { name: "Body hair", description: "Hair on the body and around the genitals.", variants: ["Shaved", "Trimmed", "Natural"] },
        { name: "Piercings", description: "Piercings on a partner's body." },
        { name: "Tattoos", description: "Tattoos on a partner's body." },
      ],
    },
    {
      name: "Clothing",
      icon: "t-shirt",
      description: "Outfits, materials, and what is (or isn't) worn.",
      items: [
        { name: "Lingerie", description: "Sexy underwear and intimate outfits.", roles: ["Wearing", "Partner wearing", "Shopping together"] },
        { name: "Leather", description: "Clothing and gear made of leather.", roles: ["Wearing", "Partner wearing"], variants: ["The smell"] },
        { name: "Latex and rubber", description: "Tight, shiny synthetic outfits.", roles: ["Wearing", "Partner wearing"], variants: ["Full body"] },
        { name: "Stockings and tights", description: "Leg wear that changes the look and feel of legs.", roles: ["Wearing", "Partner wearing"], variants: ["Tearing them"] },
        { name: "High heels", description: "Heels as part of the look, the posture, or the play.", roles: ["Wearing", "Partner wearing"], variants: ["Worship"] },
        { name: "Uniforms", description: "Outfits tied to a job or role.", roles: ["Wearing", "Partner wearing"] },
      ],
    },
    {
      name: "Toys",
      icon: "magic-wand",
      description: "Devices and tools made for pleasure.",
      items: [
        { name: "Vibrators", description: "Toys that vibrate for external or internal stimulation.", roles: ["Using on myself", "Using on a partner", "Partner using on me"] },
        { name: "Dildos", description: "Non-vibrating toys for penetration.", roles: ["Using on myself", "Using on a partner", "Partner using on me"], variants: ["Double-ended"] },
        { name: "Butt plugs", description: "Anal toys shaped to stay in place.", roles: ["Wearing", "Partner wearing"], variants: ["Small", "Medium", "Large", "Worn for hours"] },
        { name: "Cock rings", description: "Rings worn at the base of the penis for firmness and sensation.", roles: ["Wearing", "Partner wearing"], variants: ["Vibrating"] },
        { name: "Strap-ons", description: "A harness that holds a dildo for penetration.", roles: ["Wearing", "Receiving"] },
      ],
    },
    {
      name: "Locations",
      icon: "map-pin",
      description: "Where it happens.",
      items: [
        { name: "Bedroom", description: "The classic, private setting.", variants: ["Your place", "Partner's place", "Hotel"] },
        { name: "Shower and bath", description: "Anywhere with water.", variants: ["Shower", "Bath", "Hot tub", "Pool"] },
        { name: "Outdoors", description: "Out in nature.", variants: ["Forest", "Beach", "Garden", "Balcony"] },
        { name: "Car", description: "In or on a vehicle.", variants: ["Back seat", "Front seat", "Parked somewhere quiet"] },
        { name: "Public places", description: "Places where you could get caught.", variants: ["Bathroom", "Changing room", "Office", "Elevator"] },
        { name: "Kitchen", description: "Counters, tables, and whatever is in the fridge.", variants: ["Counter", "Table", "With food"] },
      ],
    },
    {
      name: "Roleplay",
      icon: "mask-happy",
      description: "Acting out characters and scenarios.",
      items: [
        { name: "Teacher and student", description: "An authority and learning scenario between adults.", roles: ["Teacher", "Student"], variants: ["Detention"] },
        { name: "Doctor and patient", description: "A medical exam scenario.", roles: ["Doctor or nurse", "Patient"] },
        { name: "Boss and employee", description: "A workplace power scenario.", roles: ["Boss", "Employee"], variants: ["Job interview"] },
        { name: "Maid or butler", description: "A service scenario with orders and chores.", roles: ["Giving orders", "Serving"], variants: ["French maid outfit"] },
        { name: "Police and suspect", description: "An arrest and interrogation scenario.", roles: ["Officer", "Suspect"] },
        { name: "Strangers", description: "Acting like you just met.", variants: ["Bar pickup", "Online date"] },
      ],
    },
    {
      name: "Sensation",
      icon: "hand",
      description: "Playing with touch, temperature, and texture.",
      items: [
        { name: "Sensory play", description: "Playing with touch, sound, taste, and smell.", roles: ["Giving", "Receiving"], variants: ["Feathers", "Textures"] },
        { name: "Hot wax", description: "Dripping warm candle wax on skin.", roles: ["Giving", "Receiving"] },
        { name: "Ice play", description: "Using cold to contrast with warm skin.", roles: ["Giving", "Receiving"] },
        { name: "Tickling", description: "Tickling as play, tease, or torment.", roles: ["Giving", "Receiving"], variants: ["Light", "Intense", "Feathers", "While restrained"] },
      ],
    },
    {
      name: "Bondage",
      icon: "link",
      description: "Restraint and restriction using rope, cuffs, and other gear.",
      items: [
        { name: "Rope bondage", description: "Tying someone up for restraint or for the look of it.", roles: ["Tying", "Being tied"], variants: ["Shibari", "Suspension"] },
        { name: "Cuffs", description: "Cuffs for wrists or ankles.", roles: ["Cuffing", "Being cuffed"], variants: ["Metal", "Fuzzy"] },
        { name: "Blindfolds", description: "Taking away sight to sharpen everything else.", roles: ["Blindfolding", "Being blindfolded"] },
        { name: "Gags", description: "Something in or over the mouth to muffle speech.", roles: ["Gagging", "Being gagged"], variants: ["Ball gag", "Tape"] },
        { name: "Spreader bars", description: "A bar that keeps legs or arms apart.", roles: ["Using", "Being restrained"] },
        { name: "Restraint furniture", description: "Furniture built for tying someone in place.", roles: ["Using", "Being restrained"], variants: ["St. Andrew's cross"] },
      ],
    },
    {
      name: "Pain and impact",
      icon: "lightning",
      description: "Striking, pinching, and biting, from playful to intense.",
      items: [
        { name: "Spanking", description: "Striking the butt or thighs with a hand or paddle.", roles: ["Giving", "Receiving"], variants: ["Hand", "Paddle", "Over clothes", "Bare"] },
        { name: "Flogging", description: "A multi-tailed flogger across the back, butt, or thighs.", roles: ["Giving", "Receiving"] },
        { name: "Caning", description: "A thin, flexible cane that gives sharp, precise strokes.", roles: ["Giving", "Receiving"], variants: ["Light", "Heavy"] },
        { name: "Nipple play", description: "Pinching, clamping, or pulling the nipples.", roles: ["Giving", "Receiving"], variants: ["Pinching", "Clamps", "Weights"] },
        { name: "Hair pulling", description: "Holding or tugging hair during sex or kissing.", roles: ["Doing", "Receiving"], variants: ["Gentle", "Firm"] },
      ],
    },
    {
      name: "Power and control",
      icon: "crown",
      description: "Dominance, submission, and who gets to decide.",
      items: [
        { name: "Power exchange", description: "One person takes control and the other gives it up, by agreement.", roles: ["Dominant", "Submissive", "Switch"] },
        { name: "Orgasm control", description: "Deciding when, how, or if someone gets to come.", roles: ["In control", "Being controlled"], variants: ["Edging", "Denial", "Needing permission"] },
        { name: "Chastity", description: "A device that blocks touching or getting off.", roles: ["Wearing", "Keyholder"] },
        { name: "Pet play", description: "Taking on an animal persona and being treated like one.", roles: ["Pet", "Owner"], variants: ["Puppy", "Kitten"] },
      ],
    },
    {
      name: "Watching and being watched",
      icon: "eye",
      description: "Audiences, cameras, and screens.",
      items: [
        { name: "Exhibitionism and voyeurism", description: "Watching others, or being watched, during sex or undressing.", roles: ["Being watched", "Watching"], variants: ["Public", "Semi-public"] },
        { name: "Photos and video", description: "Recording intimate moments.", roles: ["Filming or photographing", "Being filmed or photographed"], variants: ["Photos", "Video"] },
      ],
    },
    {
      name: "Taboo and edge play",
      icon: "warning-diamond",
      description: "Widely off-limits or higher-risk play. Always between consenting adults, with research and care.",
      items: [
        { name: "Age play", description: "Roleplay where consenting adults act older or younger.", roles: ["Caregiver", "Little"] },
        { name: "Watersports", description: "Play involving urine.", roles: ["Giving", "Receiving"], variants: ["Golden shower", "Marking"] },
      ],
    },
  ],
};
