/**
 * Writes the current database content back into the typed seed files, so the repo can be kept
 * in sync with what editors changed on the site.
 *
 *   bun run db:export-seed          export the published versions (what visitors see)
 *   bun run db:export-seed --draft  export the drafts instead
 *
 * Ids are written too, so reseeding from these files keeps every share link and export valid.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { asc } from "drizzle-orm";
import { translationEntries, type PublishedData } from "../lib/kinks/published";
import { loadDraft, loadLatestVersion } from "./content";
import { closeDb, db } from "./index";
import { lists } from "./schema";

const OUT_DIR = path.join(import.meta.dir, "seed-data");
const q = (value: string) => JSON.stringify(value);

function identifier(slug: string) {
  const camel = slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
  return /^[a-z_]/i.test(camel) ? camel : `list${camel}`;
}

function renderList(data: PublishedData) {
  const lines = [`import type { SeedList } from "@/lib/kinks/types";`, ``, `export const ${identifier(data.slug)}: SeedList = {`];
  lines.push(`  slug: ${q(data.slug)},`, `  name: ${q(data.name)},`, `  tagline: ${q(data.tagline)},`, `  description: ${q(data.description)},`, `  categories: [`);
  for (const category of data.categories) {
    lines.push(`    {`, `      id: ${category.id},`, `      name: ${q(category.name)},`, `      icon: ${q(category.icon)},`, `      description: ${q(category.description)},`, `      items: [`);
    for (const item of category.items) {
      const roles = item.options.filter((o) => o.kind === "role");
      const variants = item.options.filter((o) => o.kind !== "role");
      const parts = [`id: ${item.id}`, `name: ${q(item.name)}`, `description: ${q(item.description)}`];
      if (roles.length) parts.push(`roles: [${roles.map((o) => q(o.label)).join(", ")}]`);
      if (variants.length) parts.push(`variants: [${variants.map((o) => q(o.label)).join(", ")}]`);
      if (item.options.length) parts.push(`optionIds: [${[...roles, ...variants].map((o) => o.id).join(", ")}]`);
      lines.push(`        { ${parts.join(", ")} },`);
    }
    lines.push(`      ],`, `    },`);
  }
  lines.push(`  ],`, `};`, ``);
  return lines.join("\n");
}

async function main() {
  const draft = process.argv.includes("--draft");
  const rows = await db.select({ slug: lists.slug }).from(lists).orderBy(asc(lists.sortOrder), asc(lists.name));
  const exported: PublishedData[] = [];
  for (const { slug } of rows) {
    const data = draft ? await loadDraft(slug) : (await loadLatestVersion(slug))?.parsed;
    if (data) exported.push(data);
    else console.warn(`Skipping ${slug}: no ${draft ? "draft" : "published version"}.`);
  }

  await mkdir(OUT_DIR, { recursive: true });
  for (const data of exported) await writeFile(path.join(OUT_DIR, `${data.slug}.ts`), renderList(data));

  const index = [
    `import type { SeedList } from "@/lib/kinks/types";`,
    ...exported.map((d) => `import { ${identifier(d.slug)} } from "./${d.slug}";`),
    ``,
    `export const seedLists: SeedList[] = [${exported.map((d) => identifier(d.slug)).join(", ")}];`,
    ``,
  ];
  await writeFile(path.join(OUT_DIR, "index.ts"), index.join("\n"));

  const translations = exported.flatMap((d) => translationEntries(d.translations));
  const translationFile = [
    `/**`,
    ` * Content translations applied on seed: \`{ locale, entityKey, field, value }\`.`,
    ` * Entity keys are \`l:slug\`, \`c:id\`, \`i:id\`, or \`o:id\`. Generated by \`bun run db:export-seed\`.`,
    ` */`,
    `export const seedTranslations: { locale: string; entityKey: string; field: string; value: string }[] = [`,
    ...translations.map((t) => `  { locale: ${q(t.locale)}, entityKey: ${q(t.entityKey)}, field: ${q(t.field)}, value: ${q(t.value)} },`),
    `];`,
    ``,
  ];
  await writeFile(path.join(OUT_DIR, "translations.ts"), translationFile.join("\n"));

  console.log(`Exported ${exported.length} lists and ${translations.length} translations from the ${draft ? "drafts" : "published versions"}.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(closeDb);
